name: komodo_dex
description: Multicoin Wallet with DEX gateway

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.9.1+1

publish_to: none

environment:
  sdk: ">=2.8.1 <3.0.0"

# We're using specific (pinned) plugin versions in order to help us review the dependency upgrades.
# KomodoPlatform plugin upgrades should be created as new branches, with PR into master;
# commits from such branches can be referenced in this YAML (ref) under a TODO section that mentions the branch.
# cf. https://github.com/ca333/komodoDEX/pull/695#issuecomment-592236296

dependencies:
  flutter: # flutter.dev
    sdk: flutter

  flutter_localizations: # flutter.dev
    sdk: flutter


  #-----flutter.dev, dart.dev--------


  path_provider: 2.0.11 # flutter.dev (Note: Supports null safety)

  shared_preferences: 2.0.15 # flutter.dev (Note: Supports null safety)

  url_launcher: 6.1.5 # flutter.dev (Note: Supports null safety)

  local_auth: 1.1.11 # flutter.dev (Note: Supports null safety)

  http: 0.13.4 # dart.dev (Note: Supports null safety)

  crypto: 3.0.1 # dart.dev (Note: Supports null safety)


  #-------fluttercommunity.dev------


  connectivity_plus: # newly added, wasn't reviewed
    git:
      url: https://github.com/KomodoPlatform/plus_plugins.git
      path: packages/connectivity_plus/connectivity_plus/
      ref: d293b60a77313cc697542724f00186cb09187103 #2.3.6

  
  package_info_plus: # newly added, wasn't reviewed
    git:
      url: https://github.com/KomodoPlatform/plus_plugins.git
      path: packages/package_info_plus/package_info_plus/
      ref: 08a7a35502d2498ea3dd1473445b4511dea35518 #1.4.2

  share_plus: ^4.5.3



  #------------3rd party-------------


  audioplayers: # last reviewed 859c88c2c3fe926bdbb6e5e729d3c16d088be76a
    git:
      url: https://github.com/KomodoPlatform/audioplayers.git
      path: packages/audioplayers/
      ref: 9b927167b0bc103bee43042c195e881b8f653964 #0.20.0

  file_picker: # last reviewed 627c0a31b22026809cea3c5cb3c0a81d2a632117
    git:
      url: https://github.com/KomodoPlatform/flutter_file_picker.git
      ref: f72d4b70c4c63ade584e64b7706774555fbc1c8e #4.2.5

  # provider: # last reviewed 0c1394af0ae2422dba43f5d36f0e45ea75f849a3
  #   git:
  #     url: https://github.com/KomodoPlatform/provider.git
  #     ref: 960e422105e2b7a6a9e46b2517daead8754c6b25 #6.0.2
  provider: ^6.0.5


  encrypt: # last reviewed b17327a
    git:
      url: https://github.com/KomodoPlatform/encrypt
      ref: 3a42d25b0c356606c26a238384b9f2189572d954 #5.0.1

  qr_flutter: # last reviewed 587c969052f37d9fc0f14801aba241bffbc1ea84
    git:
      url: https://github.com/KomodoPlatform/qr.flutter.git
      ref: e3f8d3d4bbe8661f6c941acde8c9815a876756a3 #4.0.0

  auto_size_text: # last reviewed a2cb00e548916731f5c4c241d79a93419a4f9447
    git:
      url: https://github.com/KomodoPlatform/auto_size_text.git
      ref: 2178f0821132636bc4f0dea1bc4d40a889d8249b #3.0.0

  mobile_scanner: # newly added, never reviewed
    git:
      url: https://github.com/KomodoPlatform/mobile_scanner.git
      ref: 9ecb3d8c0fc34533b007270cd425264c4b446008 #1.1.2

  bip39: # last reviewed 3bee3eedb28ba5ae1af82873c8e5b6f32038b8a1
    git:
      url: https://github.com/KomodoPlatform/bip39-dart.git
      ref: 3633daa2026b98c523ae9a091322be2903f7a8ab #1.0.6

  pin_code_view: # last reviewed c0b6516 -> da9f0f4 by yurii-khi
    git:
      url: https://github.com/KomodoPlatform/pin_code_view.git
      ref: da9f0f4a7b315f05e6d7e9f3f3d3a3644d7c042f

  intl_generator: # newly added, wasn't reviewed
    git:
      url: https://github.com/KomodoPlatform/intl_generator.git
      ref: 1d1f98f291b2cffc80f4a2822024b3722312e571 #0.2.1

  flutter_svg: # last reviewed 03ed93a576381f2369bd05f8b833a2273705fe69
    git:
      url: https://github.com/KomodoPlatform/flutter_svg.git
      ref: 02b8595a5b1f1d97c8af5e4a2f84e790bcd8b460 #0.23.0+1

  sqflite: # last reviewed 8da4eefdd8b13dfe7eedbd5dea1c1dded7d04acf
    git:
      url: https://github.com/KomodoPlatform/sqflite.git
      path: sqflite/
      ref: 85d84b6f656764e4a4d6632dcc9913f4f47011e5 #2.0.0+4
  
  flutter_secure_storage: # last reviewed eef67d3d006b2c53453df183f7d4ac081948e110
    git:
      url: https://github.com/KomodoPlatform/flutter_secure_storage.git
      path: flutter_secure_storage/
      ref: 26efe91a75228ad8c8626d6eea18f7f3cb21bdd9 #5.0.2
 
  flutter_slidable: # last reviewed 27bbe0dfa9866ae01e8001267e873221ef5fbd67
    git:
      url: https://github.com/KomodoPlatform/flutter_slidable.git
      ref: 175b0735f5577dd7d378e60cfe2fe1ca607df9fa #1.1.0
  
  decimal: # last reviewed 93fcaabe2da686b1987a351a03a70e86edf6504f
    git:
      url: https://github.com/KomodoPlatform/dart-decimal.git
      ref: 16aeee1354b74bb83a84e5f37b7b6976a02400df #1.4.0

  # MRC: Argon2 algo was our only remaining use of flutter_sodium, so I have switched
  # to dargon2_flutter, which does only Argon2, therefore dropping our dependency on
  # flutter_sodium completely
  dargon2_flutter: # reviewed by MRC at d11f51cab560acf7644ebef402f1996b6f320365
    git:
      url: https://github.com/KomodoPlatform/dargon2
      path: dargon2_flutter/dargon2_flutter/
      ref: d11f51cab560acf7644ebef402f1996b6f320365 #3.1.0

  uuid: # last reviewed 981adcac181443e3def4ced76a43b96c534e68ce
    git:
      url: https://github.com/KomodoPlatform/dart-uuid.git
      ref: c9a37bc675fd3fa715db2d929dc66d15ec09ad27 #3.0.5

  flutter_bloc: # Last reviewed 32d5002fb8b8a1e548fe8021d8468327680875ff
      git:
        url: https://github.com/KomodoPlatform/bloc.git
        path: packages/flutter_bloc/
        ref: 32d5002fb8b8a1e548fe8021d8468327680875ff # 8.1.1

  # "Flutter Favorite" plugin (https://docs.flutter.dev/packages-and-plugins/favorites)
  flutter_local_notifications: ^12.0.4 # TODO: Secure code review of this plugin.
  


dev_dependencies:
  integration_test:
    sdk: flutter

  # recommended linter rules
  flutter_lints: 1.0.4 # flutter.dev (Note: Supports null safety)
  

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/branding/logo_app.png"
  image_path_ios: "assets/branding/ios_app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/branding/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/branding/
  - assets/branding/svg/
  - assets/audio/
  - assets/mocks/
  - assets/currency-flags/
  - assets/language-flags/
  - assets/coin-icons/
  - assets/svg/
  - assets/svg_light/
  - assets/swap_share/
  - assets/coins.json
  - assets/coins_config_tcp.json
  - assets/rebranding/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
    - family: Monospace
      fonts:
        - asset: fonts/Monospace/RobotoMono-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
